global:
  smtp_smarthost: 'postfix:25'
  smtp_from: 'alertmanager@749ep.site'

route:
  receiver: 'email-notifications'
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 4h  
  group_by: [alertname, datacenter, app]

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'emailtest@diginey.com'
    send_resolved: false
    html: "{{ range .Alerts }}{{ .Annotations.description }}<br>{{ end }}"
    require_tls: false