global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'calc-app'
    static_configs:
    - targets: ['calc-app:8080']

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

rule_files:
  - alert.rules.yml
