prometheus-node-exporter:
  enabled: false

server:
  service:
    type: NodePort
    nodePort: 30900

alertmanager:
  service:
    type: NodePort
    nodePort: 30903

  config:
    global:
      smtp_smarthost: 'postfix-mail:587'
      smtp_from: 'alertmanagerk8s@749ep.site'
    route:
      receiver: 'email-notifications'
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 4h  
      group_by: [alertname, datacenter, app]
    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: 'emailtest@diginey.com'
        send_resolved: false
        html: "{{ range .Alerts }}{{ .Annotations.description }}<br>{{ end }}"
        require_tls: false

serverFiles:
  prometheus.yml:
    scrape_configs:
    - job_name: 'calc-app'
      static_configs:
      - targets: ['calc-app:8080']
    rule_files:
    - /etc/config/alerting_rules.yml

  alerting_rules.yml:
    groups:
    - name: default
      rules:
      - alert: APITimeTriggered
        expr: increase(api_root_time_accessed_total[5m]) > 0
        for: 30s
        labels:
          severity: critical
        annotations:
          description: "Root API endpoint (time retrieval) was accessed."
      - alert: SumOperationRequested
        expr: increase(api_sum_requested_total[5m]) > 0
        for: 30s
        labels:
          severity: critical
        annotations:
          description: "Sum operation was requested."
      - alert: ResultDeletion
        expr: increase(api_delete_triggered_total[5m]) > 0
        for: 30s
        labels:
          severity: critical
        annotations:
          description: "A result was deleted."